In [89]:
import pandas as pd

dados = pd.read_csv('car-prices.csv')
dados.head()

   Unnamed: 0  mileage_per_year  model_year      price sold
0           0             21801        2000   30941.02  yes
1           1              7843        1998   40557.96  yes
2           2              7109        2006   89627.50   no
3           3             26823        2015   95276.14   no
4           4              7935        2014  117384.68  yes

In [90]:
a_renomear ={
    'mileage_per_year':'milhas_por_ano',
    'model_year':'ano_do_modelo',
    'price':'preco',
    'sold':'vendido'
}
dados = dados.rename(columns = a_renomear)
dados.head(10)

   Unnamed: 0  milhas_por_ano  ano_do_modelo      preco vendido
0           0           21801           2000   30941.02     yes
1           1            7843           1998   40557.96     yes
2           2            7109           2006   89627.50      no
3           3           26823           2015   95276.14      no
4           4            7935           2014  117384.68     yes
5           5           14661           2007   55405.26     yes
6           6            9990           2002   93415.61     yes
7           7           11599           2008   65265.09      no
8           8            7834           1999   43917.53     yes
9           9           14913           2003  107860.41     yes

In [91]:
trocar = {
    'yes':1,
    'no':0
}
dados.vendido = dados.vendido.map(trocar)
dados

      Unnamed: 0  milhas_por_ano  ano_do_modelo      preco  vendido
0              0           21801           2000   30941.02        1
1              1            7843           1998   40557.96        1
2              2            7109           2006   89627.50        0
3              3           26823           2015   95276.14        0
4              4            7935           2014  117384.68        1
...          ...             ...            ...        ...      ...
9995        9995           15572           2006   97112.86        0
9996        9996           13246           2002  107424.63        1
9997        9997           13018           2014   93856.99        0
9998        9998           10464           2011   51250.57        1
9999        9999           12362           1999   87945.73        0

[10000 rows x 5 columns]

In [92]:
from datetime import datetime

ano_atual = datetime.today().year
dados['idade_do_modelo'] = ano_atual - dados.ano_do_modelo
dados.head()

,Unnamed: 0,milhas_por_ano,ano_do_modelo,preco,vendido,idade_do_modelo
0,0,21801,2000,30941.02,1,20
1,1,7843,1998,40557.96,1,22
2,2,7109,2006,89627.50,0,14
3,3,26823,2015,95276.14,0,5
4,4,7935,2014,117384.68,1,6

In [93]:
dados['km_por_ano'] = (dados.milhas_por_ano) * 1.60934
dados.head()

,Unnamed: 0,milhas_por_ano,ano_do_modelo,preco,vendido,idade_do_modelo,km_por_ano
0,0,21801,2000,30941.02,1,20,35085.22134
1,1,7843,1998,40557.96,1,22,12622.05362
2,2,7109,2006,89627.50,0,14,11440.79806
3,3,26823,2015,95276.14,0,5,43167.32682
4,4,7935,2014,117384.68,1,6,12770.11290

In [94]:
dados = dados.drop(columns = ['Unnamed: 0',"milhas_por_ano",'ano_do_modelo'])
dados.head(10)

       preco  vendido  idade_do_modelo   km_por_ano
0   30941.02        1               20  35085.22134
1   40557.96        1               22  12622.05362
2   89627.50        0               14  11440.79806
3   95276.14        0                5  43167.32682
4  117384.68        1                6  12770.11290
5   55405.26        1               13  23594.53374
6   93415.61        1               18  16077.30660
7   65265.09        0               12  18666.73466
8   43917.53        1               21  12607.56956
9  107860.41        1               17  24000.08742

In [95]:
x = dados[['preco','idade_do_modelo','km_por_ano']]
y = dados['vendido']
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score
import numpy as np

# Retirar aleatoriedade
np.random.seed(42)

raw_treino_x, raw_teste_x, treino_y, teste_y = train_test_split(x,y,
                                                        test_size=0.25,
                                                        #Manter a proporção corretamente, de acordo com a saída
                                                        stratify=y)

scaler = StandardScaler()
scaler.fit(raw_treino_x)
treino_x = scaler.transform(raw_treino_x)
teste_x = scaler.transform(raw_teste_x)

modelo = LinearSVC()
modelo.fit(treino_x, treino_y)
previsoes = modelo.predict(teste_x)

acuracia = accuracy_score(teste_y, previsoes)
print('A acurácia foi de %.2f%%' % (acuracia*100))

A acurácia foi de 70.12%

In [96]:
from sklearn.dummy import DummyClassifier

dummy_statified = DummyClassifier()
dummy_statified.fit(treino_x,treino_y)
previsoes = dummy_statified.predict(teste_x)

acuracia = accuracy_score(teste_y, previsoes)*100
print('A acurácia do dummy foi %.2f%%' % acuracia)

A acurácia do dummy foi 52.64%

/usr/local/lib64/python3.7/site-packages/sklearn/dummy.py:132: FutureWarning: The default value of strategy will change from stratified to prior in 0.24.
  "stratified to prior in 0.24.", FutureWarning)

In [97]:
dummy_statified = DummyClassifier()
dummy_statified.fit(treino_x,treino_y)
dummy_statified.score(teste_x,teste_y)

# acuracia = accuracy_score(teste_y, previsoes)*100
# print('A acurácia do dummy foi %.2f%%' % acuracia)

0.5036

In [98]:
from sklearn.svm import SVC

# Retirar aleatoriedade
np.random.seed(42)

raw_treino_x, raw_teste_x, treino_y, teste_y = train_test_split(x,y,
                                                        test_size=0.25,
                                                        #Manter a proporção corretamente, de acordo com a saída
                                                        stratify=y)

scaler = StandardScaler()
scaler.fit(raw_treino_x)
treino_x = scaler.transform(raw_treino_x)
teste_x = scaler.transform(raw_teste_x)

modelo = SVC()
modelo.fit(treino_x, treino_y)
previsoes = modelo.predict(teste_x)

acuracia = accuracy_score(teste_y, previsoes)
print('A acurácia foi de %.2f%%' % (acuracia*100))

A acurácia foi de 76.04%

In [99]:
from sklearn.tree import DecisionTreeClassifier

# Retirar aleatoriedade
np.random.seed(42)

raw_treino_x, raw_teste_x, treino_y, teste_y = train_test_split(x,y,
                                                        test_size=0.25,
                                                        #Manter a proporção corretamente, de acordo com a saída
                                                        stratify=y)

scaler = StandardScaler()
scaler.fit(raw_treino_x)
treino_x = scaler.transform(raw_treino_x)
teste_x = scaler.transform(raw_teste_x)

modelo = DecisionTreeClassifier()
modelo.fit(treino_x, treino_y)
previsoes = modelo.predict(teste_x)

acuracia = accuracy_score(teste_y, previsoes)
print('A acurácia foi de %.2f%%' % (acuracia*100))

A acurácia foi de 71.64%

In [104]:
from sklearn.tree import export_graphviz
import graphviz

features = x.columns
dot_data = export_graphviz(modelo, out_file=None,
                           filled = True, rounded = True,
                           feature_names = features,
                          class_names = ["não", "sim"])
grafico = graphviz.Source(dot_data)
grafico